### ISSUE TITLE
Nested <a/> tags compiled inncorectly

### ISSUE THREAD

**Issue by ESKempken** [twig-component-tools/tct-bundle#7]
Input / Expected output
```
<a>
  <p>test</p>
  <a>test</a>
  <p>test</p>
</a>
```

Output 
```
<a>
  <p>test</p>
</a>
<a>test</a>
<p>test</p>
```

**Comment by barthy-koeln** [comment]
Can you please verify if this applies only to "a" tags?

AFAIK nested "a" tags are invalid HTML.

Browsers are very tolerant of HTML errors, but this bundle might not be.

Barthy

**Comment by ESKempken** [comment]
Guess its a mute point. It also effect `<p/>` tags, but similarly they should also not be nested.

**Comment by ESKempken** [comment]
Yeah, Its a problem of invalid nesting. Nesting `h1` (not atomic innitials) has the same effect
